# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY a433-microservices/package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY a433-microservices/ .

# Expose port 3000
EXPOSE 3000

# Define the command to run your app
CMD ["node", "index.js"]
